//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamBoatService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VariableNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VariableNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamBoatService.Properties.VariableNames", typeof(VariableNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent Wind Angle.
        /// </summary>
        internal static string AWA {
            get {
                return ResourceManager.GetString("AWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent Wind Speed.
        /// </summary>
        internal static string AWS {
            get {
                return ResourceManager.GetString("AWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat Speed.
        /// </summary>
        internal static string BSP {
            get {
                return ResourceManager.GetString("BSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string COURSE {
            get {
                return ResourceManager.GetString("COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        internal static string DEPTH {
            get {
                return ResourceManager.GetString("DEPTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        internal static string HDG {
            get {
                return ResourceManager.GetString("HDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string LAT {
            get {
                return ResourceManager.GetString("LAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string LON {
            get {
                return ResourceManager.GetString("LON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Mark TWA.
        /// </summary>
        internal static string NEXTMARKTWA {
            get {
                return ResourceManager.GetString("NEXTMARKTWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Wind Angle.
        /// </summary>
        internal static string TWA {
            get {
                return ResourceManager.GetString("TWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Wind Direction.
        /// </summary>
        internal static string TWD {
            get {
                return ResourceManager.GetString("TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Wind Speed.
        /// </summary>
        internal static string TWS {
            get {
                return ResourceManager.GetString("TWS", resourceCulture);
            }
        }
    }
}
